export const interests = [
  "Nature exploration",
  "Pet adoption",
  "Fitness training",
  "Singing",
  "Hiking",
  "Cooking",
  "Photography",
  "Traveling",
  "Reading",
  "Gardening",
  "Art and crafts",
  "Writing",
  "Music concerts",
  "Yoga",
  "Dancing",
  "Volunteering",
  "Watching movies",
  "Board games",
  "Fashion",
  "Food tasting",
  "Camping",
  "Learning new languages",
  "Surfing",
  "Skydiving",
  "Meditation",
  "Fishing",
  "Painting",
  "Motorcycling",
  "Snowboarding",
  "Wine tasting",
];
